# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: admin
  host: localhost
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: admin
  host: localhost
  password:

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: project_production
#   pool: 5
#   username: admin
#   password:

cucumber:
  <<: *TEST
